baseURL = ""
languageCode = 'en-us'
title = 'My Site'
theme = "hugo-book"

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
