baseURL = ""
languageCode = 'en-us'
title = 'My Site'
theme = "hugo-book"



# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1
