baseURL = ""
languageCode = 'en-us'
title = '~/Nimish 🇮🇳'
theme = "hugo-book"



# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1
